### ISSUE TITLE
Org-mode integration causes load failure

### ISSUE THREAD

**Issue by amitp** [ppareit/graphviz-dot-mode#17]
If org mode isn't loaded already, the recently added org-mode integration causes an error. To reproduce, I ran `emacs -q`, then:

```emacs-lisp
(load-file "~/.emacs.d/elpa/graphviz-dot-mode-20151010.2359/graphviz-dot-mode.el")
```

I get this error: `(void-variable org-src-lang-modes)`

I believe the reason is that `eval-after-load` needs its argument wrapped up in a quote. Instead of:

```
(eval-after-load 'org-mode
    (add-to-list 'org-src-lang-modes  '("dot" . graphviz-dot)))
```

it should be

```
(eval-after-load 'org-mode
   '(add-to-list 'org-src-lang-modes  '("dot" . graphviz-dot)))
```

**Comment by heartnheart** [comment]
I can confirm the problem and solution.

**Comment by tathanhdinh** [comment]
I can confirm too this issue.

**Comment by baiger** [comment]
I can confirm this too

**Comment by ppareit** [comment]
amitp, your suggested change has been committed, thanks!
