### ISSUE TITLE
graphviz-dot-preview error

### ISSUE THREAD

**Issue by decoursin** [ppareit/graphviz-dot-mode#21]
When I run `graphviz-dot-preview`, I get "No Image found." and nothing happens. Does anybody know what's going on?

**Comment by daveloyall** [comment]
Internally, `graphviz-dot-mode` runs `dot` with some arguments to generate the image file.

It checks the output of that process for lines beginning with the word `Warning`.

There is a bug, it should check for lines beginning with the word `Error`, too.  But it doesn't, so sometimes it will fail and the behavior you will see is "nothing happens", as you describe.

You could alter the defun for `graphviz-dot-preview` to confirm or deny that you are experiencing the same issue I describe.

**Comment by decoursin** [comment]
Thanks, but I'm no longer using graphviz. I mean it worked well for what I was doing, but I'm finished with that. Good luck!

**Comment by textarcana** [comment]
Hey I just installed graphviz-dot-mode via Emacs package manager, and I have the same problem. Any advice as to what I should do to patch the defun of `graphviz-dot-preview`?

**Comment by daveloyall** [comment]
I don't really remember the details of this.. but I did find that I have a slightly modified `graphviz-dot-preview` function here: https://github.com/daveloyall/graphviz-dot-mode/commit/22b72c6eda0d46299ce2cd721330f358b70e83fc

**Comment by ppareit** [comment]
Fixed in latest version
