### ISSUE TITLE
colors substrings of words that are not keywords

### ISSUE THREAD

**Issue by ppareit** [ppareit/graphviz-dot-mode#3]
bug:

===== test.dot==========
digraph G {
    credit -> blueberry
}

shows the characters "red" and "blue" in red colour

**Comment by josteink** [comment]
I've had a similar issue in one of my own modes.

You can easily solve this by wrapping the color/keyword expression within word-delimiters tags. See this for an example:

https://github.com/josteink/wsd-mode/blob/master/wsd-mode.el#L139-L141

**Comment by ppareit** [comment]
Thanks for the link. Looking into this today and it seems like it is no longer an issue. Maybe the font lock mechanism has changed in Emacs. I'm closing this, but don't hesitate to reopen if this persists.
