### ISSUE TITLE
company-mode based completions

### ISSUE THREAD

**Issue by prasannakog** [ppareit/graphviz-dot-mode#50]
Though this major mode supports completions it is better to provide them through company completions. I could see a company backend but I don't how to use it

**Comment by ppareit** [comment]
Company support is a recent addition. Documentation needs to be
updated. I'll leave this issue open.

**Comment by ppareit** [comment]
The following code is part of my `emacs.el` and could be helpful:
````elisp
(use-package graphviz-dot-mode
  :config
  (setq graphviz-dot-indent-width 4))

(use-package company-graphviz-dot
  )
````

**Comment by ppareit** [comment]
Fixed in the documentation
