### ISSUE TITLE
font-lock-reference-face has been removed from Emacs

### ISSUE THREAD

**Issue by ericsfraga** [ppareit/graphviz-dot-mode#65]
This face had been marked as obsolete for some time, I guess, and it has now been removed from the development version of Emacs. Solution is to use a different font lock face, I guess, but I have no idea which one would be most relevant.

**Comment by ppareit** [comment]
Thanks for the heads up!

Would not mind a PR.

**Comment by ericsfraga** [comment]
You're welcome and, okay, I'll see if I can do something this week.

**Comment by ppareit** [comment]
Seem a good substitution.

**Comment by epost** [comment]
Thanks for spotting this @ericsfraga! This was causing org-babel fontification errors in case of source blocks with options in them, such as this one:

```org
#+begin_src dot
digraph {
  rankdir=LR
  a->b
}
#+end_src
```

I made a PR with your suggested fix.

@ppareit Hartelijk bedankt voor deze prachtige Emacs modus! :) 🙏 💯

**Comment by ppareit** [comment]
Perfect. I'm pulling this right now. Thanks to both!

**Comment by ericsfraga** [comment]
Excellent. Thank you!
