### ISSUE TITLE
Native compilation error: No such file or directory, company

### ISSUE THREAD

**Issue by Andre0991** [ppareit/graphviz-dot-mode#66]
Hi!

I got this error after installing `graphviz-dot-mode`:

```
company-graphviz-dot.el:34:2: Error: Cannot open load file: No such file or directory, company
```

I suppose the error is harmless, since the other files were compiled correctly and the major mode works fine.

Still, it would be nice to only execute code in `company-graphviz-dot.el` if requiring `company` succeeds.

WDYT?

**Comment by ppareit** [comment]
`graphviz-dot-mode` depends on `company` for the autocomplete functionality. If I would implement this now, I would implement it in a different way as to not be dependent on company. Emacs has it's own autocomplete framework and company can tap into this. A future revision should go this route.
