### ISSUE TITLE
Could you please consider supporting capf or corfu？

### ISSUE THREAD

**Issue by nowislewis** [ppareit/graphviz-dot-mode#67]
I wonder if there is a way to not rely on company but use capf, so that packages like corfu can also use the wonderful completion. 

I used to be a company user, but now I really like the way corfu completes, and the out-of-order completion experience it has with orderless. Maybe supporting capf would be a good option for Graphviz-dot-mode?

Anyway, thank you  for the great work, graphviz-dot-mode is already a part of my work and life.

**Comment by ppareit** [comment]
Yes, this is Issue #66. Definitely should be changed. I'll close this one and keep #66 open.
