### ISSUE TITLE
Warnings while package install with MELPA

### ISSUE THREAD

**Issue by vochor** [ppareit/graphviz-dot-mode#9]
Hi,

When I install the package with MELPA, Emacs reports following warnings:

> Leaving directory `/home/myUser/.emacs.d/elpa/graphviz-dot-mode-20140303.1301'
> 
> Compiling file /home/myUser/.emacs.d/elpa/graphviz-dot-mode-20140303.1301/graphviz-dot-mode-pkg.el at Sun Feb  8 02:18:37 2015
> Entering directory `/home/myUser/.emacs.d/elpa/graphviz-dot-mode-20140303.1301/'
> 
> Compiling file /home/myUser/.emacs.d/elpa/graphviz-dot-mode-20140303.1301/graphviz-dot-mode.el at Sun Feb  8 02:18:37 2015
> graphviz-dot-mode.el:399:1:Warning: (lambda (elm) ...) quoted with ' rather
>    than with #'
> graphviz-dot-mode.el:402:1:Warning: (lambda (elm) ...) quoted with ' rather
>    than with #'
> graphviz-dot-mode.el:405:1:Warning: (lambda (elm) ...) quoted with ' rather
>    than with #'
> 
> In graphviz-dot-mode:
> graphviz-dot-mode.el:542:9:Warning: `compilation-parse-errors-function' is an
>    obsolete variable (as of 24.1); use`compilation-error-regexp-alist'
>    instead.
> graphviz-dot-mode.el:543:7:Warning: reference to free variable `dot-menu'
> 
> In graphviz-dot-compilation-parse-errors:
> graphviz-dot-mode.el:599:4:Warning: Use `with-current-buffer' rather than
>    save-excursion+set-buffer
> graphviz-dot-mode.el:625:12:Warning: Use`with-current-buffer' rather than
>    save-excursion+set-buffer
> graphviz-dot-mode.el:625:12:Warning: `goto-line' is for interactive use only;
>    use`forward-line' instead.
> 
> In graphviz-dot-view:
> graphviz-dot-mode.el:842:11:Warning: assignment to free variable `novaproc'
> 
> In graphviz-dot-complete-word:
> graphviz-dot-mode.el:929:29:Warning: (lambda (elm) ...) quoted with ' rather
>    than with #'

I am using Debian jessie with GNU Emacs 24.4.1

Regards

**Comment by andreareina** [comment]
I can confirm this also happens with 

* macOS 10.11
* GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)
* graphviz-dot-mode 20171103.127

Output below:

```
Leaving directory `/Users/[...]/.emacs.d/elpa/graphviz-dot-mode-20171103.127'

Compiling file /Users/[...]/.emacs.d/elpa/graphviz-dot-mode-20171103.127/graphviz-dot-mode-pkg.el at Thu Apr  5 13:19:11 2018
Entering directory `/Users/[...]/.emacs.d/elpa/graphviz-dot-mode-20171103.127/'

Compiling file /Users/[...]/.emacs.d/elpa/graphviz-dot-mode-20171103.127/graphviz-dot-mode.el at Thu Apr  5 13:19:11 2018

In graphviz-dot-mode:
graphviz-dot-mode.el:555:50:Warning: `compilation-parse-errors-function' is an
    obsolete variable (as of 24.1); use `compilation-error-regexp-alist'
    instead.
graphviz-dot-mode.el:556:9:Warning: reference to free variable `dot-menu'

In graphviz-dot-compilation-parse-errors:
graphviz-dot-mode.el:611:4:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
graphviz-dot-mode.el:637:12:Warning: Use `with-current-buffer' rather than
    save-excursion+set-buffer
graphviz-dot-mode.el:637:12:Warning: `goto-line' is for interactive use only;
    use `forward-line' instead.


```
